version: '2.1'

services:

  app:
    stdin_open: true
    tty: true
    build: ./python
    image: tweet-app
    volumes:
      - ./python:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db


  db:
    build: ./postgres
    image: tweet-db
    environment:
         POSTGRES_USER: "postgres"
         POSTGRES_PASSWORD: "postgres"
         POSTGRES_DB: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h db -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"




volumes:
  postgres-data:
    driver: local
      # These commands correspond to -i and -t in docker run...
    #stdin_open: true
    #tty: true

#restart:


  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   build: ./postgres
  #   volumes:
  #     - .:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #     POSTGRES_DB: "postgres"
  #   ports:
  #     - "5432:5432"
  #
# volumes:
#   - ./testData

    #/var/lib/postgresql/data



          # data:
          #   image: postgres:9.6
          #   volumes:
          #     - /var/lib/postgresql
          #   command: "true"
